import Image from "next/image";
import {Canvas} from '@react-three/fiber'
import { SunFilledIcon, MoonFilledIcon } from "@/components/icons";
import { Navbar } from "@/components/navbar";
import {clsx} from "clsx"
import {Metadata} from 'next'

import { title, subtitle } from "@/components/primitives";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home({ font }: {font: string}) {

  return (

      <main className="inline-block text-center gap-8 items-center">
      <span className={title()}>A&nbsp;</span>
        <span className={title({ color: "red" })}>UIC Made&nbsp;</span>
        <br />
        <span className={title()}>
          tectonic plate simulation
        </span>
        <div className={subtitle({ class: "mt-4" })}>
         Designed by David Love
        </div>
      </main>  

    
  );
}
